import "../styles/globals.scss";
import type { AppProps } from "next/app";
import Head from "next/head";
import { RecoilRoot } from "recoil";
import SnackBar from "../components/alert/SnackBar";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <RecoilRoot>
        <Component {...pageProps} />
        <SnackBar />
      </RecoilRoot>
    </>
  );
}

export default MyApp;
